= Basic Deployment of Ansible Automation Platform 2.5
:navtitle: Home

== Introduction

Red Hat® Ansible® Automation Platform offers a simple solution to deploying applications. It gives you the power to deploy multi-tier applications reliably and consistently, all from one common framework. You can configure key services as well as push application files from one common system. And rather than writing custom code to automate your systems, your team writes simple task descriptions that even the newest team member can understand—saving not only upfront costs, but making it easier to react to change over time.

Duration: 60 minutes

== Objectives

On completing this course, you should be able to:

- Understanding of the Ansible Automation Platform's (AAP) features, architecture, and components.
- Discover how to evaluate the infrastructure needs and set up the environment for the deployment of AAP.
- Know the benefits of using the right Topology for the deployment. 

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

 - Amrinder Singh (Content Architect)
 - Rutuja Deshmukh (Editor)
 - Anna Swicegood (Learning Product Manager)

== Prerequisites

This course assumes that you have the following prior experience:

- Foundational knowledge of Linux, Containers, Ansible, and OpenShift. 
