#!/usr/bin/env bash
#

echo "Starting build process..."
echo "Removing old site..."
rm -rf ./www/*
echo "Building new site..."

sed -i "s/^name:[[:space:]]*.*/name: modules/" antora.yml

podman run --rm --name showroom-builder --platform linux/amd64 \
  -v "./:/antora:z" \
  docker.io/antora/antora --stacktrace default-site.yml  

sed -i "s/^name:[[:space:]]*.*/name: basic_deployment_aap2.5/" antora.yml

echo "Build process complete. Check the ./www folder for the generated site."
echo "To view the site locally, run the following command: utilities/lab-serve"
echo "If already running then browse to http://localhost:8080/index.html"
