= On-premise Installation 

There are 3 different ways by which you can do the installation to your local infrastructure i.e. Rpm, Containerized, and Operator. In this, we are going to learn about the Future of Deployment method which is known as Containerized installation. The RPM installation is more or less the same and as the RPM will be getting deprecated in the future our focus will be on understanding the other 2 Containerized and Operator-based deployment. 


System Requirement 

Since the Container and Operator-based deployment needs 3000 IOPS (input/output operations per second) compared to the VM base Deployment of 1500 IOPS please refer to the below Guides while doing the deployment: 

RPM: The https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/platform-system-requirements[System requirements, window=_blank ] section of RPM installation. 			

Containerized: The https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/containerized_installation/aap-containerized-installation#system_requirements[System requirements, window=_blank ] section of Containerized installation. 			

For https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/ocp-topologies#tested_system_configurations_6[System requirements, window=_blank ] for installing Ansible Automation Platform on OpenShift Container Platform, see the Tested system configurations section of Tested deployment models. 